### ISSUE TITLE
ASM zlib build on Windows gives erroneous results

### ISSUE THREAD

**Issue by weltling** [madler/zlib#41]
The bug happens using an ASM optimized static zlib 1.2.5 or 1.2.7 on Windows x86. Supposed is to have no output, but currently it outs "%Cë". Non ASM versions on Windows do that right, as well both ASM and non ASM builds on Linux. The bad data can be fetched from http://188.40.74.4/corrupted.gz .

Using the snippet and data from

https://gist.github.com/anonymous/2c5a88ca9ac6f4c2a064

the erroneous behavior is reproducible. 

It is possible, that the same issue does exist on Darwin, but sadly I've no such OS to test. This bug is originally detected in PHP https://bugs.php.net/bug.php?id=61677 .

**Comment by madler** [comment]
What assembly code is being used?  There are a few in zlib's contrib directory.  By the way, the stuff in the contrib directory is not part of zlib.  It is just there as a convenience and is supported (or not) by those third-party contributors.  What I will do is simply remove the offending code from the next distribution.

**Comment by rhuijben** [comment]
@madler All the 'standard' Windows project files for Visual Studio make it much to easy to enable these optimizations from the 'contrib' directory, while there are still known issues. These users just assume that because the project files are supported, all settings are too. (See also issue #274)

**Comment by timofonic** [comment]
@yuexiaoyun  @TomDataworks @wzv5  @rhuijben @weltling @maitrihegde @tannerhelland @ngyuki @ch3cooli @weltling @madler @jk3064 Does this happen in zlib-ng? https://github.com/Dead2/zlib-ng

**Comment by madler** [comment]
Due to bugs and other issues, the assembler code in the contrib directory has been removed.

**Comment by weltling** [comment]
To mention were also, that we stopped to use any ASM implementations in PHP back then. C versions do no issues for years already, and combined with PGO there's no impact on performance. If those ASM files aren't supported anymore, it is right' that they shouldn't show up in the distribution.

Thanks.

**Comment by pcordes** [comment]
@weltling:

> and combined with PGO there's no impact on performance.

That's probably because the asm isn't tuned very well for modern x86 (http://agner.org/optimize/).  I had a look at `contrib/masmx64/inffas8664.asm` and there are things like partial-register stalls and false dependencies, and sub-optimal sequences for doing `foo &= (1<<count)-1;`  (e.g. `bts` is more efficient than a variable-count shift).  And using `rsp` as the struct pointer (not exception safe!) is a bad choice: every `[rsp+const]` memory operand takes an extra byte to encode vs. using any other register.

The `memcpy` strategy for short copies is also suspect.  Using `rep movsw` + a branch to optionally copy one extra byte might possible work well, but for small lengths you can probably do *much* better with an unaligned XMM load / store which writes more than you need, as long as you aren't close to the end of the output buffer.

`contrib/amd64/amd64-match.S` has room for improvement, too.  (And probably USE_SSE would be a win on modern CPUs, especially Skylake, where unaligned load penalties are lower.  Especially with some tuning to improve efficiency).

**Comment by pcordes** [comment]
@madler: Is zlib interested in "officially" including any new asm?  Or at least in an optional but easy-to-use way that some Linux distro packages might enable?

And what about runtime dispatching to use BMI1/BMI2 instructions, and/or AVX instructions?  Intel CPUs run plain variable-count shifts as 3 uops (because of x86 legacy baggage with FLAGS semantics in case the count is zero), and there's a lot of bit shifting, so `shlx` / `shrx` are a nice win on their own.  The other BMI instructions are also quite nice.  (And `lzcnt`/`tzcnt` are significantly faster on AMD than `bsr` / `bsf`).

Compilers know how to use BMI1/BMI2 instructions when compiling ordinary C, for example `foo = bar & ((1<<count) - 1` can compile to a BZHI instruction.  So runtime dispatching could be orthogonal to hand-written asm, building a baseline version and a BMI2 version for a few important functions.  There is some compiler support for doing this automatically (GNU C `ifunc`), or there are various ways to do it manually (e.g. function pointers, although with Spectre just being announced, introducing new indirect branches into a library used all over the place might be a bad idea...)
