### ISSUE TITLE
Please make new release

### ISSUE THREAD

**Issue by kloczek** [madler/zlib#422]
Last zlib version has been released more than two years ago.
I think that it would be good to make new release ASAP :)

**Comment by tpgxyz** [comment]
@kloczek well you can use snapshot :)

**Comment by kloczek** [comment]
Issue is that most of the Linux and other OSes distributions are using only releases and only for handful packages some snapshots :)

**Comment by plo-** [comment]
@madler what about it? Is this repo still maintained? At least to merge some PRs (like #420)?

**Comment by madler** [comment]
Yes, there will be a tagged release soon.

**Comment by jaykrell** [comment]
Ubuntu has one commit that Debian lacks. This should help clear that up. Thank you.

**Comment by kamronbatman** [comment]
@madler, status on new release?

**Comment by okias** [comment]
since there is lot of coming changes (optimization) to zlib [1], would you consider releasing another version? 

I'd like to see zlib without direct dependency on Google developers, but incorporate their patches and release often is sign of vital project...

[1] https://webengineshackfest.org/2019/slides/chromium-updates-from-arm-higher-faster-stronger-by-dave-rodgman-and-adenilson-cavalcanti.pdf

**Comment by plo-** [comment]
Hello @madler! It's been a while, do you have a release date for this new release?

**Comment by brlcad** [comment]
Hi @madler.  Like everyone else, wondering what the status of zlib is...

**Comment by xavier2k6** [comment]
madler commented on 18 Jun 2019
> Yes, there will be a tagged release soon.

@madler -> 9 months later, Is this baby ready to show it's head? 😆

**Comment by Alanscut** [comment]
Hi @madler , may I ask when this masterpiece can be born?

**Comment by xavier2k6** [comment]
> madler commented on 18 Jun 2019
> 
> > Yes, there will be a tagged release soon.
> 
> @madler -> 9 months later, Is this baby ready to show it's head? 😆

@madler Any status update at least? - It's been a year since you said there'd be a tagged release.

**Comment by harkue** [comment]
@madler Any status update at least? - It's been more than a year since you said there'd be a tagged release.

**Comment by libxengine** [comment]
haha ,then two years passed .....

**Comment by Videogamer555** [comment]
Despite us @-ing MAddler, he doesn't respond. I'm pretty sure that this is a dead project. Despite the fact that ZLib compression can be found everywhere (the deflate algorithm invented by MAddler and used in ZLib is also found in many other projects, even in the original zip file format which was used by PKZip and WinZip software), it seems that either MAddler himself has died, or he's given up working on this project (a project that if it never existed, would mean no Deflate algorithm, and thus no internet would exist, nor would most other computer software). Did you know that most internet traffic is compressed by either GZip container or raw Deflate stream? Yeah, it's THAT IMPORTANT of an invention. I seriously hope that @madler will get back to work on this VERY important project, or at least let us all know that he's given up on it (something that hopefully won't happen, because it could mean the end of modern computer technology and the internet as we know it).

**Comment by gbloice** [comment]
Maybe time to consider [zlib-ng?](https://github.com/zlib-ng/zlib-ng)

**Comment by broonie** [comment]
Note that there's more than one fork out there - for example there's also one that the Chromium people have. One thing that having releases from upstream zlib would help with would be helping with bringing things together.

**Comment by okias** [comment]
There is million forks, since everyone fixed what bothered them, but I think it's reasonable to focus on relatively independent and maintainer forks, which zlib-ng fulfills :wink:

**Comment by broonie** [comment]
As does the Chromium one to some extent :(

**Comment by Neustradamus** [comment]
I think that it is needed to look all PRs (contributions of people) and Issues of this repo.

**Comment by vielmetti** [comment]
#605 and #603 should be addressed in a new release that fixes CVE-2018-25032.

**Comment by Neustradamus** [comment]
There is a 1.2.12 but it is not "perfect".

**Comment by vielmetti** [comment]
@Neustradamus If there are specific issues, please report them!

**Comment by Neustradamus** [comment]
@vielmetti: You can already look recent entries here:
- https://github.com/madler/zlib/issues
- https://github.com/madler/zlib/pulls

**Comment by madler** [comment]
> There is a 1.2.12 but it is not "perfect".

It's not?! Oh my goodness. I'm shocked.

**Comment by Neustradamus** [comment]
@madler: Not perfect only because it fails to compile:
- https://github.com/madler/zlib/pull/607
- https://github.com/madler/zlib/issues/608
- https://github.com/madler/zlib/issues/609
- https://github.com/madler/zlib/pull/610

**Comment by madler** [comment]
Thanks. The first two which are issues with zlib are both fixed by a new commit on the develop branch. The other two are from contributions. The contributor provided a patch for #610, for which there is a new commit. The CMakeLists.txt thing is not a problem if you compile normally without using the assembler code options. I have asked for someone to edit CMakeLists.txt to remove those options.

**Comment by madler** [comment]
Made new release!
