### ISSUE TITLE
improve inflate decompressing speed

### ISSUE THREAD

**Issue by MrMehdi** [madler/zlib#442]
hi i have a question 
i want improve zlib inflate decompressing routine
is any idea about this?
how can i use a fixed Huffman trees for efficient decoding?
i see a inffixed.h ,whats this file?
thx for your attention

**Comment by madler** [comment]
You can force fixed coding when compressing using Z_FIXED. However it may not provide any improvement in decoding speed, if that's what you're after. Relatively little time is spent interpreting the dynamic code headers. The most direct way to reduce the decompression time is to reduce the size of the compressed data. To keep it small, you need to use the normal dynamic coding. Going to fixed coding will usually slow down decompression, since the amount of compressed data is larger.
