### ISSUE TITLE
MemorySanitizer, use of uninitialized in slide_hash zlib/deflate.c:219:20

### ISSUE THREAD

**Issue by alexhultman** [madler/zlib#518]
#517

While fuzzing, uninitialized memory allocated in zcalloc is eventually used in:

  | #0 0x53443d in slide_hash zlib/deflate.c:219:20
  | #1 0x52b179 in fill_window zlib/deflate.c:1516:13
  | #2 0x53b4d0 in deflate_fast zlib/deflate.c:1838:13
  | #3 0x531e70 in deflate zlib/deflate.c:1003:18

Version of zlib is 1.2.11 compiled with proper -fsanitize=memory flags on x64 Linux. I can provide more info if needed, including reproducing code.

**Comment by madler** [comment]
As noted in the comment immediately below line 219 of deflate.c, "If n is not on any hash chain, prev[n] is garbage but its value will never be used." The sliding of those uninitialized values do not affect the output of deflate.

**Comment by alexhultman** [comment]
Do you have any interest in making zlib compatible with MemorySanitizer or should I consider it a bad idea to fuzz zlib with msan?

**Comment by stweil** [comment]
@madler, could you consider a code update which uses full memory initialisation when zlib is build for fuzzing? In that case performance is not an issue because code which is instrumented for fuzzing is slow anyway. I found this issue because of this fuzzing bug report:

https://oss-fuzz.com/testcase-detail/5084378994180096

As you can see other projects use zlib (not surprising) and get error reports which cost time to analyze and comment.

**Comment by nmoinvaz** [comment]
There are a few functions such as `__msan_unpoison` that can be used also.
