### ISSUE TITLE
Where does the algo of deflateBound come from?

### ISSUE THREAD

**Issue by apexpeng** [madler/zlib#549]
Hi, Community:

I am studying the logic of gzip & zlib now. Found a code block to define the dest buffer length:

```
    /* conservative upper bound for compressed data */
    complen = sourceLen +
              ((sourceLen + 7) >> 3) + ((sourceLen + 63) >> 6) + 5;
```

Sorry for troubling, but I do not understand this algo:

- Why set to `(sourceLen + (8 -1)) /8) `? I do not understand the number 8.
- And the number in `((sourceLen + 63) >> 6) + 5` means?

**Comment by madler** [comment]
As noted in the comments for that function, it is an estimate of the upper bound when using fixed blocks. This would be acheived with no matches and all 9-bit encoded literals (literals in the range 144..255). For that case, n/8 is the number of bytes added due to expanding every byte to 9 bits, and the n/64 is an approximation of the number of bytes added by the block overhead of 10 bits (3 block description bits and 7 end code bits) for every 127 bytes of input for the lowest `memLevel`. That would around one more byte for every 100 bytes of input, so 1/64 overestimates that while avoiding division, using shifts instead. The `+5` covers the zero case for an empty stored block.
