### ISSUE TITLE
ln: failed to create symbolic link 'libz.so': Operation not permitted

### ISSUE THREAD

**Issue by piyushether** [madler/zlib#556]
Hi,

While installing zlib package from the source code, running make command (after ./configure), I am encountering an error "ln: failed to create symbolic link 'libz.so': Operation not permitted". I am very new to zlib so I do not know much about this error. I tried to search on internet but couldn't get a proper solution. Please help me to resolve this issue.

**Comment by mscastanho** [comment]
@piyushether the `install` target will probably try to install the library to a system-wide location, which will require running `make install` as a privileged user. Did you run it with `sudo` or as user `root`?

**Comment by piyushether** [comment]
@mscastanho yes I tried with Audi but still it is working. I tried to install zlib at `/use/local/zlib`. It was working previously but not this time. performing `make` Itself provides an error not make install.

**Comment by madler** [comment]
Is `make install` exactly the command you are typing? Are you setting an environment variable to give the destination directory? Why do you want to install it in `/usr/local/zlib`? That will put the include file in `/usr/local/zlib/include` and the library in `/usr/local/zlib/lib`. Then you will need to specify those locations to the compiler every time, whereas the compiler is already looking in the default locations, `/usr/local/include` and `/usr/local/lib`. Did you create the `zlib` directory in `/usr/local`?

(In your answers, especially exactly what you're typing, please check your spelling. You spelled `/usr/local/zlib` and `/use/local/zlib` here, I think you meant sudo when you put in Audi, and on stackoverflow you typed `/usr/lcoal/zlib` instead of `/usr/local/zlib`.)

**Comment by piyushether** [comment]
Thank you for pointing out typos. As I mentioned previously, I am encountering an error when I do `make`,  `make install` is the later step. Firstly, I performed `./configure --prefix=/usr/local/zlib/ ` following by `make`, and here I received an error of symbolic link. Once this will resolve then only I can go for `sudo make install`. I want to install zlib as a supportive library for hdf, netcdf, and also for couple of models, and therefore to avoid conflict with the system, I want to install in `/usr/lcoal/zlib`.

**Comment by madler** [comment]
(You didn't check your spelling again.)

Now I'm confused as to when the symbolic link error is occurring. Is it on the `make` or the `make install`?

Please do a `make clean`, go through all of your steps in order, and then copy the commands and responses as one thing, and paste into a comment here.

**Comment by piyushether** [comment]
I am facing an error on `make` .
I did `make clean`  and followed all the steps. First, I did `./configure --prefix=/usr/local/zlib/`, which run successfully. Later, I did `make`, which provides an error of symbolic link.

**Comment by madler** [comment]
Please copy the entire session and paste here.

**Comment by piyushether** [comment]
Sorry for the delayed response. I rectified a problem and resolved it. I was trying to install zlib from the shared folder in my Virtualbox and that shared folder can not access the system file in Virtualbox. So, finally, I copied the zlib source file to my home folder and I installed it. Thank you
