### ISSUE TITLE
zlib-1.2.11.tar.gz is deleted?

### ISSUE THREAD

**Issue by daohu527** [madler/zlib#649]
protobuf depends on `zlib-1.2.11.tar.gz` and the url `https://zlib.net/zlib-1.2.11.tar.gz` is broken!!!

Why delete zlib-1.2.11.tar.gz directly?

**Comment by madler** [comment]
It was moved, not deleted. You can change the link to `https://zlib.net/fossils/zlib-1.2.11.tar.gz`.

**Comment by victorygogogo** [comment]
why delete 1.2.11.tar.gz ,   it is so rude, can you provide it by the old url ?

**Comment by QGB** [comment]
https://www.zlib.net/zlib-1.2.11.tar.xz

**Comment by akontsevoy** [comment]
Deleting or moving or otherwise invalidating what's supposed to be permalinks is generally a bad practice -- it breaks a ton of dependent projects for no good reason (as is evidenced by the above PR/issue references). It's really disappointing to see surprises like that from such veterans as zlib maintainers. Surely it is well-known that if the web server directory structure must be rejiggered, symlinks from the old to the new file locations (in /fossils) should be made, or HTTP redirects should be provided.
The only arguable reason (that I can think of) to invalidate links to old versions are security vulnerabilities in those versions. But even so, I must argue that keeping dependencies secure and up to date should be the business of the parent projects' maintainers, not those of the child project.

**Comment by madler** [comment]
They are always in http://zlib.net/fossils/ , including the latest version, never deleted nor moved. If you want a permanent link (until I die and the domain renewal doesn't get paid that is), then link there.

You can also download any version from https://github.com/madler/zlib/tags .

**Comment by akontsevoy** [comment]
@madler Understood; but if versioned files go into /fossils, it is unclear why the current version in web root (e.g. https://zlib.net/zlib-1.3.1.tar.gz ) has a version in it, and turns into a dead link each time a new version comes out. I suppose it made sense 20 years ago, when the download section listed multiple mirrors, to have all mirrored downloads named consistently. But now that there is only one mirror, could not the current link be version-neutral (e.g. https://zlib.net/zlib-latest.tar.gz ) and always point to the latest version, whatever it is at the moment?
That would also help people who want to reference the latest zlib in their build jobs (but cannot git-clone master branch for some reason).

**Comment by madler** [comment]
@akontsevoy  Such a link is also there, and is noted on zlib.net page: https://zlib.net/current/zlib.tar.gz . You may want to read the zlib.net home page, as you may find other things there you find useful.

**Comment by akontsevoy** [comment]
I sit corrected! :blush: Been looking at that page for half an hour, FAQ and historical versions too; I should have been more attentive.
But even so, the rationale behind download links going dead with each new release still eludes me.

**Comment by selvipal** [comment]
Is the zlib site down? Not even the home page is loading for me
