### ISSUE TITLE
inflate can return Z_BUF_ERROR even with a very large output buffer

### ISSUE THREAD

**Issue by mterrisse** [madler/zlib#719]
[TestInflate.zip](https://github.com/madler/zlib/files/9734277/TestInflate.zip)

Hello,
I wrote a small program TestInflate.cpp attached to this report because I have a corrupted array of bytes that makes our code run into a very long loop and an out of memory error: indeed inflate returns Z_BUF_ERROR even with a very large output buffer, so our code tries to allocate more memory again and again for this buffer.
Since the data looks corrupted, I think it should return Z_DATA_ERROR or similar error code. That's why I report it here.

To compile and run this code I did:
- git clone https://github.com/madler/zlib.git
- ./configure
- make
- clang++ TestInflate.cpp libz.a -o TestInflate
- ./TestInflate

What am I supposed to do when inflate returns Z_BUF_ERROR?
Should I consider that the data is incomplete or corrupted if avail_in = 0 and avail_out > total_out?

Thank you for your help.
Regards,

Michel Terrisse

**Comment by madler** [comment]
What you're supposed to do is look at `avail_out`. If `avail_out` is not zero, and you have provided all of your compressed data, and you are getting `Z_OK` or `Z_BUF_ERROR`, then your compressed data has ended prematurely. There is _no point_ in providing more output space, since if `avail_out` is not zero, `inflate()` has already done all it can with the input provided. There is no error in the compressed data you have provided _so far_, so there is no `Z_DATA_ERROR`.

Only if `avail_out` is zero is it possible that `inflate()` needs more output space to continue the operation.

**Comment by mterrisse** [comment]
Thank you very much for this very clear answer.
Regards,
Michel Terrisse
