### ISSUE TITLE
Add support for building under Visual Studio 2013

### ISSUE THREAD

**Issue by DanKonigsbach** [madler/zlib#78]
The changes to support Visual Studio are bundled in pull request #77.  (I tried to make two, independent pull requests, but messed up.)

**Comment by yuslepukhin** [comment]
I am building via CMake and it works all right but the docs say I need to use nmake. Which way to go?

**Comment by jasonwilliams200OK** [comment]
Since VS2015 for the first time supporting C99, I have submitted two similar PR to libgd and libuv:

* https://github.com/libgd/libgd/pull/192
* https://github.com/libuv/libuv/pull/532

@madler, if this is acceptable for libz, I can pull together a PR against develop branch. It will also take away the [related comments](https://github.com/madler/zlib/blob/50893291621658f355bc5b4d450a8d06a563053d/gzguts.h#L97-L101) from the code base and provide a proper snprintf fallback implementation of `snprintf` for versions of VS less than 1900 (VS2015). What do you think?

**Comment by tbeu** [comment]
See also #114 for snprintf on VS2015.

**Comment by jasonwilliams200OK** [comment]
@tbeu, would be nice if you modify your commit to incorporate proper fallback to snprintf (which is not _snprintf). Also providing the fallback as external hook mimics the auto config approach and follows the separation of concerns.

**Comment by tbeu** [comment]
Yes, I know, that snprintf is different to _snprintf. But _snprintf is used all the years in zlib thus there is no urgent requirement to add snprintf fallback.
