### ISSUE TITLE
Codes for reserved symbols are rejected even if unused

### ISSUE THREAD

**Issue by Storyyeller** [madler/zlib#82]
If PKZIP_BUG_WORKAROUND is not defined, zlib will incorrectly reject inflating files that contain definitions for literal/length symbols 286 and 287 or distance symbols 30 or 31, even if they are unused. 

As far as I can tell, this should be allowed by the standard. Ironically, this behavior means that simply taking the table used for mode 01 and using it in a mode 10 block will result in zlib rejecting the file.

**Comment by madler** [comment]
The rejection is correct.  You should note that the RFC does in fact explicitly restrict the literal/length symbol values to < 286.  The RFC however erroneously and inconsistently permits distance symbol values 30 and 31.  I have elected to reject both in order to assure the early rejection of invalid streams.  There is no benefit and only detriment to providing code for symbols that are not used.

As another example, the RFC does not explicitly state that a dynamic block must define a code for end-of-block.  However if you don't, the deflate stream can never terminate.  zlib's inflate requires a definition of an end-of-block code in a dynamic block or the stream is rejected.  This assures that when, for example, random data is fed to inflate it will soon reject the stream as invalid.

**Comment by Storyyeller** [comment]
By the way, it is not true that there is no benefit to providing code for symbols that are not used. It is theoretically possible to have a case where doing so allows for a smaller compression.

For example, suppose that distance codes 20-29 are all zero, but distance code 19 is not 0. If you are not allowed to specify explicit codes for 30 and 31, then you only have 10 consecutive zeros, meaning that you would have to use some combination of 0, 16, and/or 17 to represent them in the huffman encoding of the code lengths. If you are allowed to specify the unused distance codes, you could just use a single 18, which depending on the circumstances, could be shorter.

**Comment by Storyyeller** [comment]
By the way, it is not true that there is never any benefit to providing explicit codes for unused symbols. Since the codes are themselves huffman encoded, and runs of zeros can be encoded with a special symbol, it is theoretically possible to end up with a situation where you have less than 11 trailing zeros, and adding in the "unused" zeros would allow you to encode the code lengths more compactly.

**Comment by Storyyeller** [comment]
On further thought, I realized that I was wrong, It may be beneficial to provide non zero values for distance 30 and 31, since the distance codes are restricted to forming a huffman tree. That would allow to have say, 32 5s, instead of 28 5s and 2 3s, or whatever.

So theoretically, there may be files where the restriction on distance codes 30 and 31 increases the number of bits required for the compressed representation.
