### ISSUE TITLE
Please add deflateGetDictionary function

### ISSUE THREAD

**Issue by jagiller** [madler/zlib#89]
Please add deflateGetDictionary function. It will be useful in streaming mode (after sync flush) when inflateGetDictionary and deflateGetDictionary can be used to get dictionary on both sides to be used as preset dictionary for another compression algorithm when it is needed to change compression algorithm due to channel speed change.

**Comment by folays** [comment]
I also have a small use case in modifying an existing software, where I have access to a z_stream in deflate mode, and where I miss deflateGetDictionary().

The output stream is 1/ deflated and 2/ encrypted.

I need to transfert the handling of the following components from a frontend to another host (a backend):
- the network file descriptor of a network peer (well, relaying layer-5 content of TCP data between the frontend and the backend)
- the z_stream
- the cipher keys

So far, it works, but as deflateGetDictionary() does not exist, it was necessary to patch the encryption code just to output a dummy deflate(,, Z_SYNC_FLUSH)-then-encrypted-packet.
The Z_SYNC_FLUSH helps me to do not have to export/import the deflate internal state.

I would rather not modify the encryption code (which require knowledge of the underlying procotol of the existing software) just to output a dummy deflate(,, Z_SYNC_FLUSH) encrypted packet.

I think on another layer of abstraction, that we should not assume that all network peers are always okay to receive an empty packet (without usefull data, only Z_SYNC_FLUSH).
I mean, a FLUSH synchronization on a local stream (attached to a buffer or a file) seems legit.

But we do not always have control on the code of a network peer, if the peer receives (encrypted or not) compressed data, runs into some code to take some action on it, and after decompression only got an empty packet (which was received only to Z_SYNC_FLUSH the z_stream / reset the compression state), the network peer could be confused or angry at receiving a dummy-empty packet, and close the connection.

I guess in situations where you do not have full control on all layers and both sides of z_stream operations, it could be usefull to have deflateGetDictionary(), so that a process could export the current internal state and transfer it to another process.

Thanks for your consideration.

**Comment by madler** [comment]
zlib's deflate does not always have the last window-size bytes of input saved in its internal sliding window. This is due to how zlib manages the sliding window and lookahead for matches. Even after more than window-size bytes of input have been provided, deflate may have as little as the last window size minus 258 bytes of that input in its sliding window. (258 is the maximum length of a match.) So if you need to retain the last window-sizes that you fed to `deflate()`, then you will need to save it yourself outside of zlib.

I have created the function, but I think that the utility of `deflateGetDictionary()` will be rather limited. It does reflect the data in which `deflate()` will be able to find matches in at that moment in time, so it could be fed to `inflate()` at the other end for compressed data that follows.
