### ISSUE TITLE
build in macos failed

### ISSUE THREAD

**Issue by 982945902** [madler/zlib#890]
the error reported as follow:

![image](https://github.com/madler/zlib/assets/49055103/2f74a41b-8dc8-4297-ad79-25cd2f0cfdd5)

**Comment by madler** [comment]
Something is wrong with how you are trying to compile or the setup of your compiler. zlib is developed on a Mac and builds just fine there. You would need to provide actual information about how, exactly, you are attempting this build and in what environment.

**Comment by 982945902** [comment]
> Something is wrong with how you are trying to compile or the setup of your compiler. zlib is developed on a Mac and builds just fine there. You would need to provide actual information about how, exactly, you are attempting this build and in what environment.

sorry

build tool:bazel 6.4.0-homebrew
clang: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
os: Darwin ZBMac-C02CW08SM 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:19:12 PDT 2022; root:xnu-8792.41.9~3/RELEASE_ARM64_T6020 arm64

zlib version:
```
def com_github_madler_zlib():
    http_archive(
        name = "com_github_madler_zlib",  # 2017-01-15T17:57:23Z
        build_file = "@sculib//bazel:zlib.BUILD",
        sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
        strip_prefix = "zlib-1.2.11",
        urls = [
            "https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz",
            "https://zlib.net/fossils/zlib-1.2.11.tar.gz",
            "https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz",
        ],
    )
```

build file
```
cc_library(
    name = "zlib",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    # Use -Dverbose=-1 to turn off zlib's trace logging. (#3280)
    copts = [
        "-w",
        "-Dverbose=-1",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
```

**Comment by madler** [comment]
Um yeah, no. You can't just grab all the .c and .h files and try to compile them. There is configuration required. Either you run `./configure` and `make`, or use cmake.

**Comment by Neustradamus** [comment]
@982945902: Can you try the current devel branch?
What is your results?

Thanks in advance.

**Comment by Neustradamus** [comment]
@madler: What do you think?

**Comment by madler** [comment]
I think this issue is closed.

**Comment by FrankHB** [comment]
> Um yeah, no. You can't just grab all the .c and .h files and try to compile them. There is configuration required. Either you run `./configure` and `make`, or use cmake.

Albeit a QoI issue, this can certainly be improved following the spirit of [simplicity](https://zlib.net/zlib_faq.html#faq07) by adding some more detection to define `Z_HAVE_UNISTD_H` in `zconf.h`, as already done for some other cases. That is, if `__WATCOMC__` counts, why not `__APPLE__`? Or just that `./configure` is most favorable? I find no explicitly documented policy about this, and it is a non-starter for simplicity. (Notice there is no `INSTALL` doc, and `./configure` is even not a standalone step in `README`.) Moreover, what about having things like `_LARGEFILE64_SOURCE` impliying `Z_HAVE_UNISTD_H`? This is quite confusing.

Actually the op also has no clue of the idiomatic use and has a different solution than you've mentioned, which is quite wrong compared to a proper configuration: it should have been something like `-DHAVE_UNISTD_H=1` instead of `-Wno-implicit-function-declaration`. I see the improvement would prevent such misconfiguration.
