### ISSUE TITLE
windowBits issue with Inflate for zlib format

### ISSUE THREAD

**Issue by maryamtahhan** [madler/zlib#94]
Hi 
I'm having a issue with window bits for inflate for the zlib format when window bits is set 8. A call to inflate returns a Z_DATA_ERROR with strm->msg set to: invalid window size.

**Please note** not that it should be in issue but I compress the data with deflateInit2()-->deflate()--> deflateEnd() with the same windowBits I pass to inflateInit2. So I'm trying to decompress data that is compressed with the same windowbits value.

the sequence of function calls is:
    deflateInit2()
    deflate()
    deflateEnd()
    inflateInit2()
    inflate()
    inflateEnd()

with windowBits set to 8 for deflateInit2() and inflateInit2() I get the error Z_DATA_ERROR with strm->msg set to: invalid window size.

with windowBits set to 8 for deflateInit2() and windowBits set to 0 inflateInit2() --> pass

**Comment by madler** [comment]
That is because there is a bug in deflate with windowBits == 8, so it will always for a request for 8 to 9 instead.  Then when you give 9 to inflate that has been initialized with 8, it will correctly reject the stream since it can't decompress it since the window is too small.

I don't want to change inflate to also force a 9 from 8, since other sources could in principle correctly produce a deflate stream with a 256 byte window.

This is not documented in zlib.h, which is what I will remedy.
